# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  patientportal-postgresql:
    image: enochdock/patientportalht-db:v1.3
    ports:
      - 127.0.0.1:5432:5432

  patientportal-api:
    image: enochdock/patientportalht-api:v1.3
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - patientportal-postgresql

  patientportal-web:
    image: enochdock/patientportalht-web:v1.3
    ports:
      - 127.0.0.1:9090:8080
    depends_on:
      - patientportal-api
